"use client";
import React from "react";
import DashboardTemplate from "@/components/templates/DashboardTemplate";
import { Switch } from "@mui/material";

const ProfilePage = () => {
  return (
    <DashboardTemplate>
      {/* Page header */}
      <h1 className="text-3xl font-semibold mb-8 text-gray-800">Profile</h1>

      {/* Container for profile content */}
      <div className="bg-white rounded-lg shadow-md p-6 space-y-8 max-w-5xl mx-auto">

        {/* Section: Your Profile */}
        <section>
          <h2 className="text-xl font-semibold mb-4">Your Profile</h2>
          <div className="flex items-start gap-6">
            {/* Profile image placeholder */}
            <div className="w-32 h-32 bg-gray-200 rounded-md flex items-center justify-center text-sm text-gray-500 border">
              Add Photo
            </div>

            {/* Personal Info section */}
            <div className="grid grid-cols-2 gap-4 w-full bg-gray-50 p-4 rounded-md border">
              <div>
                <p className="text-xs text-gray-500">First Name</p>
                <p className="font-medium">Janice</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Last Name</p>
                <p className="font-medium">Smith</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Date of Birth</p>
                <p className="font-medium">04-06-2005</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Phone Number</p>
                <p className="font-medium">+1 888-888-7777</p>
              </div>
            </div>
          </div>

          {/* Edit profile button (top right) */}
          <div className="text-right mt-2">
            <button className="text-sm text-blue-600 hover:underline">Edit Profile</button>
          </div>
        </section>

        {/* Section: Account Details */}
        <section>
          <h2 className="text-xl font-semibold mb-4">Details</h2>
          <div className="bg-gray-50 p-4 rounded-md border grid gap-4 max-w-md">
            <div>
              <p className="text-xs text-gray-500">Role</p>
              <p className="font-medium">Analyst</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Email Address</p>
              <p className="font-medium">janicesmith@gmail.com</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Password</p>
              <p className="font-medium">••••••••</p>
            </div>
          </div>
        </section>

        {/* Section: Two Factor Authentication */}
        <section>
          <h2 className="text-xl font-semibold mb-4">Two Factor Authentication</h2>
          <div className="bg-gray-50 p-4 rounded-md border space-y-4">
            <div className="flex justify-between items-center">
              <p className="text-sm text-gray-700">
                Add more security to your account by enabling Two Factor Authentication.
                When logging in, you will need to enter a code generated by your preferred authenticator app.
              </p>
              {/* Toggle Switch (just frontend for now) */}
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-700">Enabled</span>
                <Switch defaultChecked color="primary" />
              </div>
            </div>
          </div>
        </section>
      </div>
    </DashboardTemplate>
  );
};

export default ProfilePage;