import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:8000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
    {
      name: "Contributor",
      description: "Endpoints",
    },
    {
      name: "Organization",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "Your API Key",
    },
  },
};

const outputFile = "./api-spec.json";
const endpointsFiles = ["./src/utils/server.ts", "./src/routes/*.ts"];

swaggerAutogen()(outputFile, endpointsFiles, doc);
